# Generated by Django 5.2.7 on 2025-11-10 22:51

import django.db.models.deletion
import test_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_book_discounted_price_book_is_bestseller_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Task name')),
                ('description', models.TextField(verbose_name='Task description')),
                ('status', models.CharField(choices=[('NEW', 'new'), ('IN_PROGRESS', 'in_progress'), ('PENDING', 'pending'), ('BLOCKED', 'blocked'), ('DONE', 'done')], default=test_app.models.TaskStatus['NEW'], max_length=35, verbose_name='Task status')),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', to='test_app.category', verbose_name='category task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Subtask name')),
                ('description', models.TextField(verbose_name='Subtask description')),
                ('status', models.CharField(choices=[('NEW', 'new'), ('IN_PROGRESS', 'in_progress'), ('PENDING', 'pending'), ('BLOCKED', 'blocked'), ('DONE', 'done')], default=test_app.models.TaskStatus['NEW'], max_length=35, verbose_name='SubTask status')),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='test_app.task', verbose_name='The main task')),
            ],
            options={
                'verbose_name': 'SubTask',
                'verbose_name_plural': 'SubTasks',
                'db_table': 'subtasks',
            },
        ),
    ]
