# Generated by Django 5.2.7 on 2026-01-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_subtask_owner_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_notified_status',
            field=models.CharField(blank=True, choices=[('NEW', 'new'), ('IN_PROGRESS', 'in_progress'), ('PENDING', 'pending'), ('BLOCKED', 'blocked'), ('DONE', 'done')], max_length=35, null=True),
        ),
    ]
